accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/',views.home, name='home'),
    path('post/<int:post_id>/', views.detail, name='detail'),
    path('post/new/', views.post_new,name='new'),
    path('post/<int:post_id>/edit/',views.post_edit,name='edit'),
    path('post/main/', views.main, name='main'),
    path('post/<int:post_id>/delete',views.post_delete, name='delete'),
    path('post/<int:post_id>/comment/',views.add_comment,name='add_comment'),
    path('comment/<int:comment_id>/delete/',views.comment_delete,name='comment_delete'),
]

likelion/urls.py
from django.contrib import admin
from django.urls import path, include
import blog,accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True,null=True)

    def published(self):
        self.published_date=timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey('blog.Post',related_name='comments', on_delete=models.CASCADE)
    nickname=models.CharField(max_length=200)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now)
   
    def __str__(self):
        return self.text

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CreateUserForm(UserCreationForm):
    email=forms.EmailField(required=True)
    nickname=forms.CharField(required=True)

    class Meta:
        model=User
        fields=("username","email","nickname","password1","password2")

    
    def save(self, commit=True):
        user=super(CreateUserForm,self).save(commit=False)
        user.nickname=self.cleaned_data["nickname"]
        user.email=self.cleaned_data["email"]
        if commit:
            user.save()
        return user

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields={'title','text','author',}

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields={'nickname','text',}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .forms import CreateUserForm
from django.contrib.auth import views
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth


# Create your views here.
def signup(request):
    if request.method== "POST":
        userform=CreateUserForm(request.POST)
        print(userform.is_valid())
        if userform.is_valid():
            userform.save()
            return redirect('home')
    elif request.method=='GET':
        userform=CreateUserForm()

    return render(request, 'registration/signup.html',{"userform":userform})

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Comment
from django.utils import timezone
from .forms import PostForm,CommentForm
from django.contrib.auth.decorators import login_required

def home(request):
    posts=Post.objects
    return render(request, 'blog/home.html', {'posts':posts})

def detail(request,post_id):
    post_detail=get_object_or_404(Post, pk=post_id)
    form=CommentForm()
    return render(request, 'blog/detail.html',{'post':post_detail, 'form':form,})

def post_new(request):
    if request.method=="POST":
        form=PostForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.published_date=timezone.datetime.now()
            post.save()
            return redirect('detail',post_id=post.pk)
    else:
        form=PostForm()
    return render(request,'blog/post_new.html',{'form':form})
    

def post_edit(request, post_id):
    post=get_object_or_404(Post, pk=post_id)
    if request.method=="POST":
        form=PostForm(request.POST, instance=post)
        if form.is_valid():
            post=form.save(commit=False)
            post.published_date=timezone.datetime.now()
            post.save()
            return redirect('detail',post_id=post.pk)
    else:
        form=PostForm(instance=post)
    return render(request,'blog/post_edit.html',{'form':form})

@login_required
def main(request):
    posts=Post.objects
    return render(request, 'blog/main.html', {'posts':posts})

    
def post_delete(request,post_id):
    post= get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('home')     

def add_comment(request, post_id):
    post= get_object_or_404(Post,pk=post_id)
    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
    return redirect('detail', post_id=post.pk)
    
def comment_delete(request, comment_id):
    comment=get_object_or_404(Comment, pk=comment_id)
    post=comment.post
    comment.delete()
    return redirect('detail', post_id=post.id)

blog/templates/blog/base.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/blog.css'%}">
</head>

<body>
    <h1><strong> 블로그</strong></h1>
    <div>
        <a href="{% url 'accounts:signup' %}">sign up</a>
        <a href="{% url 'login' %}">login</a>
        <a href="{% url 'new'%}"> write</a>
        <a href="{% url 'home'%}"> home</a>
        <a href="{% url 'main' %}"> main</a>
    </div>
    {% block content %}
    {% endblock %}
</body>

blog/templates/blog/detail.html
{% extends "blog/base.html"%}

{% block content %}

    <h1>디테일</h1>
    <div>
        <h2>{{post.title}}</h2>
        <p>{{post.created_date}}</p>
        <p>{{post.text}}</p>
        
        <a href="{% url 'edit' post.id %}"> 수정</a>
        <a href="{% url 'delete' post.id%}"onclick="return confirm('정말로 삭제하시겠습니까?')"> 삭제</a>
    </div>

    <hr>

    <p>댓글{{post.comments.count}}개</p>
    <div class="form-group">
        <h4>댓글 작성</h4>
        <form method="POST" action="{% url 'add_comment' post.id %}">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="save btn btn-default">작성</button>
        </form>
    </div>

    {% for comment in post.comments.all%}
    <div>
        <br>
        <div>{{comment.created_date}}</div>
        <strong>{{comment.nickname}}</strong>
        {{comment.text|linebreaks}}
        <a href="{% url 'comment_delete' comment_id=comment.id %}" onclick="return confirm('정말로 삭제하시겠습니까?')">댓글 삭제</a>
    </div>
    {% empty%}
    <p>댓글이 없습니다</p>
    {% endfor %}
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}

    {% if user.is_active %}
    <p>{{user.username}}님 반갑습니다!</P>
    
    <p><a href="{% url 'logout'%}">logout</a></p>
    {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login'%}">login</a>
    <a href="{% url 'accounts:signup'%}">signup</a>
    {% endif %}

    {% for post in posts.all %}
        <div>
            <h2><a href="{% url 'detail' post.id %}">{{post.title}}</a></h2>
            <p>{{post.created_date}}</p>
            <p>{{post.text}}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/main.html
{% extends "blog/base.html"%}

{% block content %}

    <h1> 메인 페이지</h1>
    <div>
        <p>로그인을 해야 여기에 들어올 수 있다!</p>
    </div>

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>글 수정</h2>
    <form method="POST">
        {% csrf_token%}
        {{form.as_p}}
        <button type="submit">수정</butthon>
    </form>
{% endblock %}

blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>글쓰기 페이지</h1>
    <form method ="POSt">
        {% csrf_token %}
        {{form.as_p}}
        <button type= "submit">저장</button>
    </form>
{% endblock %}